version: "3.1"

services:
    db:
        container_name: mysqlNode
        image: mysql:5.7.12
        restart: always

        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: yourRootPassword
            MYSQL_DATABASE: DatabaseName
        volumes:
            - /home/mysql/data:/var/lib/mysql
            - /home/mysql/conf.d:/etc/mysql/conf.d
